version: '3.8'

services:
  nats-1:
    image: nats:latest
    container_name: nats-1
    command: ["-c", "/etc/nats/nats-server.conf"]
    volumes:
      - ./nats-1.conf:/etc/nats/nats-server.conf
    ports:
      - "4222:4222"  # Client connection
      - "6222:6222"  # Cluster communication
      - "8222:8222"  # Monitoring UI (http://localhost:8222)
    networks:
      - nats-cluster

  nats-2:
    image: nats:latest
    container_name: nats-2
    command: ["-c", "/etc/nats/nats-server.conf"]
    volumes:
      - ./nats-2.conf:/etc/nats/nats-server.conf
    ports:
      - "4223:4222"  # Client connection
    networks:
      - nats-cluster

  nats-3:
    image: nats:latest
    container_name: nats-3
    command: ["-c", "/etc/nats/nats-server.conf"]
    volumes:
      - ./nats-3.conf:/etc/nats/nats-server.conf
    ports:
      - "4224:4222"  # Client connection
    networks:
      - nats-cluster

networks:
  nats-cluster:
    driver: bridge